version: '2'
services:
 postgres:
  build: ./postgres
  image: ricardojob/banco
  container_name: banco
  ports: 
    - "5433:5432"
 web:
  build: ./app
  image: ricardojob/webapp
  container_name: app
  ports: 
   - "8081:8080"
  links: 
   - "postgres:host-banco" 